project:
  type: website
  output-dir: docs
  

website:
  #title: "Amber Camp"
  favicon: media/fav.png
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - teaching.qmd
      - cv.qmd
      - href: assignment.qmd
        text: CS201 Assignment
      - contact.qmd
      - icon: github
        href: https://github.com/abcamp
        target: blank
    background: info
    search: true
    pinned: true
  page-footer:
    left: © Copyright 2024, Amber Camp
    right: This website is built with [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank}
        
format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    toc: true

editor: visual