---
title: "CS201 Final Dashboard Project (Fall 2025)"
date: 11/5/25
---

## Instructions & Requirements

You have learned several new skills over the course of this semester–now it is time to showcase a few of those skills in a final dashboard project!

### Due Date

This project will be due on **Thursday, December 11 at 5:30 pm**. Extensions may be granted in extenuating circumstances if you [**arrange with me in advance**]{.underline}.

### How to Submit

There are two steps to submitting this project.

1.  Push your final dashboard assignment to GitHub.

2.  Upload your dashboard link to Canvas. It should look something like `<yourname>.github.io/dashboards/<yourdashboard>.html`.

### Requirements

You can be creative with what goes onto your dashboard, within the guidelines below. What story do you want to tell with your data? What kinds of plots or maps will you include?

Start by selecting a dataset, then create your dashboard with the following elements:

1.  A relevant title

2.  Credit to where the data came from

3.  A clear layout

4.  At least three visuals. They should either be different plot types or show different variables. (A data table doesn’t count but can complement your visuals.)

5.  At least one visual should be interactive (`plotly`/`girafe` style, not `shiny` style)

6.  All visuals should be neat, properly labeled, appropriately titled, and legible

7.  Navigation includes a link back to your website

8.  Everything should look polished and professional

9.  **Extra credit** if a *custom theme* you created is applied and plots are of similar styling (+1 pt)

10. **Extra credit** if there is a link on your personal website to your dashboard (+1 pt, show me where the link is)

Note that only one page is required, but you can do multiple pages/tabs if you like that layout better.

### Balancing Data and Text

You may choose to include text cards to contextualize your dashboard, but remember Tufte’s idea of data-ink: maximize what communicates information, and minimize what doesn’t.\
Keep explanatory text concise and purposeful—use it for orientation and insight, not narration.\
Your visuals should do most of the storytelling.

### Project Page Option

You may also choose to make a project page instead of a dashboard. Please consult with me first if this is your preference. The layout and requirements will differ slightly, but the overall expectations will be the same.

### Where to start?

Review our class activities from Weeks 10–11. In those activities, you created a dashboard repository, linked it to RStudio, built a simple dashboard, and pushed it live to your GitHub site.

Part of the challenge of this final project is managing the workflow: deciding how to store and access your data, what scripts you’ll need for your visuals, and how to make everything look cohesive and professional. Don’t forget: your dashboard should either have a meaningful name or be `index.qmd`!

You are welcome to share early versions with me for feedback before submitting your final project.

## Resources

-   [dashboards gallery](https://quarto.org/docs/gallery/#dashboards "target=_blank")

-   [dashboard layouts and sample code](https://quarto.org/docs/dashboards/layout.html "target=_blank")

## Need help?

Get in touch with me! I am still here to help. Send me a message at `amber.camp@chaminade.edu`, no matter how small of a question you have. We can arrange to meet in person or on Zoom as well. Have fun with this project!
