---
title: "CS-201: R/RStudio Installation Guide"
date: 8/21/26
---

## Overview

To be successful in CS-201, you will need to install R and RStudio and also connect them both to Git and GitHub.

### 1. Download and install R

- Visit this website: <https://cloud.r-project.org>

- Follow instructions for your own operating system. Be sure to get the **latest release (2026-06-24, Happy Hop)**, as of this document.

- Remember to both **download** and **install**

### 2. Download and install RStudio

- Visit this website: <https://docs.posit.co/ide/user/#direct-downloads-open-source>

- Follow instructions for your own operating system. Be sure to get the **latest release (2026.08, Yellow Yarrow)**, as of this document.

- Remember to both **download** and **install**

### 3. Create a GitHub Account

- [Visit Github](https://github.com/) and sign up for an account!

- Make your github profile more personal by [creating a README file](https://docs.github.com/en/account-and-profile/how-tos/profile-customization/managing-your-profile-readme)

### 4. Install and configure `git`

You might already have `git`! Let's check.

Open RStudio and click the **Terminal** tab (next to Console, in the lower-left pane). Type the command below exactly as written, then press Enter.

``` bash
git --version
```

*If you see a version number*, something like `git version 2.55.0`, you already have `git` and can skip ahead to **Configure `git`**.

*If you see an error,* anything along the lines of `command not found` or `'git' is not recognized`, follow the instructions for your operating system below.

***Mac users***

- In the Terminal, run:

``` bash
xcode-select --install
```

- A dialog box will pop up asking if you want to install the command line developer tools. Click **Install** and wait for it to finish. You do *not* need the full Xcode application from the App Store.

- When it's done, run `git --version` again to confirm.

***Windows users***

- Download and install [Git for Windows](https://git-scm.com/install/windows). Click the big download link at the top of that page.

- Run the installer. You can accept all of the default options... just keep clicking **Next**.

- **Important:** after installing, fully quit RStudio and reopen it, then run `git --version` again. RStudio won't find `git` until it has been restarted.

#### **Configure `git`**

- In RStudio, open the Terminal. Run the following commands. Be sure to **replace the username** (keep the quotation marks!) and email with your own username and email associated with your GitHub account.

``` bash
git config --global user.name "Jane Doe"
git config --global user.email janedoe@example.com
```

- Then, again in the Terminal, run the following, carefully checking that the name and email match your GitHub information:\

``` bash
git config --list --global
```

### 5. Link R Studio & Github

#### **Get and store your GitHub personal access token (PAT)**

Now you are almost ready to link your GitHub to RStudio.

**First:** What is a personal access token? From GitHub’s documentation:

> Personal access tokens (PATs) are an alternative to using passwords for authentication to GitHub when using the [GitHub API](https://docs.github.com/en/rest/overview/other-authentication-methods#via-oauth-and-personal-access-tokens) or the [command line](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#using-a-token-on-the-command-line).

In order to push your work (files, scripts, etc.) from the device you are working on to GitHub, you’ll need your PAT.

- Install the `usethis` package in `R` by running the following in the [**RStudio Console**]{.underline}:

``` bash
install.packages("usethis")
```

- A lot of text will show up in your Console. Don't panic! Wait for it to stop, and as long as you see something like the below, you are all set:

``` bash
The downloaded binary packages are in
    /var/folders/_v/_81c8d2j367c4dxnd_n09pq80000gn/T//RtmpME9OdS/downloaded_packages
>
```

- Then, run the following in the RStudio Console:

``` bash
usethis::create_github_token()
```

- Your browser will launch and take you to GitHub. Enter your GitHub password if prompted.

- Then, you’ll land on a screen titled **New personal access token**.

  - In the **Note** field, you will see some autopopulated text, like "DESCRIBE THE TOKEN'S USE CASE". Replace that text with something like `laptop` or `my_schoolwork`

  - Under **Expiration**, you can select an expiration date that feels right to you. My recommendation for this class? Either 'No expiration' or set a custom date for after the end of the semester

    - If you set an expiration date sooner than the end of the semester, you will find yourself having to do this linking process again soon!

- There is no need to change anything else on the screen—just scroll to the bottom and click the green 'Generate token' button.

- **Copy the generated PAT and keep track of it until this process is over!**

- In your RStudio Console run:

``` bash
gitcreds::gitcreds_set()
```

- Paste your PAT and press Enter to run.

  Things should run smoothly from here! (If you previously had a PAT saved, follow the prompts to replace with new credentials)

#### Final steps

- In the RStudio Console, run:

``` bash
usethis::git_sitrep()
```

- You should get something like the below in return. (Yours might be longer—I've truncated!)

```         
> usethis::git_sitrep()

── Git global (user) 
• Name: "abcamp"
• Email: "acamp@hawaii.edu"
• Global (user-level) gitignore file: ~/.gitignore
• Vaccinated: FALSE
ℹ See `usethis::git_vaccinate()` to learn more.
• Default Git protocol: "https"
```

- Finally, let's get you vaccinated and on `main`—I'll explain these in class. Run the following:

``` bash
usethis::git_vaccinate()
usethis::use_git_config(init.defaultBranch = "main")
```

- You should be all set now! You can run `usethis::git_sitrep()` once more to view your changes:

``` bash
usethis::git_sitrep()
```

Now you are ready for class!

*This guide is adapted from the [installation guide](https://nsf-all-spice-alliance.github.io/SDG-Analytics-in-R/rmarkdowns/installation_guide.html) written by Connor Flynn and Victoria DelaCruz for the All-SPICE Alliance SDG Analytics in R certificate, which in turn drew on materials from the Bren School at UC Santa Barbara.*
