---
title: "Letters of Recommendation"
author: "Amber Camp"
date: 11/18/24
---

## **Letters of Recommendation**

Writing a letter of recommendation to help you apply for study abroad programs, scholarships, fellowships, graduate programs, or jobs, is an important part of my job and I take it very seriously. I write multiple letters for my current and former students every semester, often ranging from five to ten. It takes a lot of work, and I spend about 1-3 hours for each letter. I want to write a strong letter to support your success, but I need your cooperation to help me do so. Please read below carefully.

### **1. Ask me as soon as possible, or at least 2 weeks before the deadline.**

This is because I have multiple responsibilities both within and outside IU, and my schedule fills up several weeks in advance. I will only agree to write a letter if I am confident I can allocate the time to do so.

I may accept rush requests only if I have previously written a similar letter for you, if there are minimal updates required, and if I can fit them into my schedule.

If you have multiple deadlines, this policy applies to the earliest one. Please understand that if I agree to write multiple letters for you (which is common in graduate admission applications or job applications), I may not be able to personalize/customize each letter.

Remember, snail mails require more time.

### **2. I will only agree to write a letter if I am confident I can speak positively about you.**

You must fit one of the following criteria:

-   You have taken my class and earned a grade of **at least an A**

-   You are my graduate student (i.e., I am your primary advisor)

-   You have directly worked for me and has been reviewed favorably

-   If you are currently enrolled in my course and have consistently maintained good performance up to the time of your request, I might consider writing a letter (note that this does not guarantee that I will write a letter for you again in the future, as it is contingent upon your maintaining good performance)

If you don’t think I know you well enough for a positive recommendation, do not choose me as a reference.

### **3. Provide as much information as possible to help me write a strong letter.**

A strong letter includes specific examples, so I will do my best to write such a letter, but I also need your help! I need to know why you are asking me, among other instructors you know, to write a letter. This information is particularly important if it is your first time to ask me for a letter or if you had me as a reference before but need an updated letter.

Did **my class/teaching prepare you** for the position/program you are applying for? If so, let me know, instead of expecting me to guess!

Did you do **particularly well in my course**, or **have I given you positive feedback**? If so, help me remember! I have taught and mentored many students, and I may not remember everything good that you did, or every positive feedback I gave you. (Nothing personal!)

### **4. Fill out the form**

If you have read and understood the information above, and still believe I am the best person to write a letter of recommendation for you, please complete [this survey](https://uiowa.qualtrics.com/jfe/form/SV_2sjebPspstt7nDw). Some questions are required, while others are optional. In some cases, we will set up an additional face-to-face appointment to discuss how my recommendation will help you but please complete this form first.

### **5. Close the loop**

Please consider informing me afterward about the outcome of your application, whether it is positive or negative.
